# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1a7861f0558511755371af70e7c117f5"
name = "sbaic"
application_url = "https://ghost-saved-easily.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[[webhooks.subscriptions]]
topics = [ "app/uninstalled" ]
uri = "/webhooks/app_uninstalled"

[[webhooks.subscriptions]]
uri = "/webhooks/customers_redact"
compliance_topics = [ "customers/redact" ]

[[webhooks.subscriptions]]
uri = "/webhooks/data_request"
compliance_topics = [ "customers/data_request" ]

[[webhooks.subscriptions]]
uri = "/webhooks/shop_redact"
compliance_topics = [ "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_orders,write_products,read_returns,read_legal_policies"
optional_scopes = [ ]
use_legacy_install_flow = false


[app_preferences]
url = "https://ghost-saved-easily.ngrok-free.app"

[auth]
redirect_urls = [
  "https://ghost-saved-easily.ngrok-free.app/auth/shopify/callback"
]
